CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;
INSERT INTO Cliente(id,nome) VALUES (nextval('HIBERNATE_SEQUENCE'), 'João');
INSERT INTO Cliente(id,nome) VALUES (nextval('HIBERNATE_SEQUENCE'), 'Maria');
INSERT INTO Cliente(id,nome) VALUES (nextval('HIBERNATE_SEQUENCE'), 'José');
INSERT INTO Cliente(id,nome) VALUES (nextval('HIBERNATE_SEQUENCE'), 'Ana');